"""empty message

Revision ID: f9e04f6e41f5
Revises: 268975a8e287
Create Date: 2024-01-29 22:22:28.913485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e04f6e41f5'
down_revision = '268975a8e287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heropower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strength', sa.String(), nullable=True),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('power_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], name=op.f('fk_heropower_hero_id_hero')),
    sa.ForeignKeyConstraint(['power_id'], ['power.id'], name=op.f('fk_heropower_power_id_power')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('hero_power')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero_power',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('strength', sa.VARCHAR(), nullable=True),
    sa.Column('hero_id', sa.INTEGER(), nullable=True),
    sa.Column('power_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], name='fk_hero_power_hero_id_hero'),
    sa.ForeignKeyConstraint(['power_id'], ['power.id'], name='fk_hero_power_power_id_power'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('heropower')
    # ### end Alembic commands ###
